name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nelson-rsvp-service" #Must be unique in Heroku
          heroku_email: "heroku@nelsonwu.net"
        env:
          HD_MONGO_URL: ${{ secrets.MONGO_URL }}
